(cl:defpackage hoofdprogramma-msg
  (:use )
  (:export
   "<PICKANDPLACEACTION>"
   "PICKANDPLACEACTION"
   "<PICKANDPLACEACTIONFEEDBACK>"
   "PICKANDPLACEACTIONFEEDBACK"
   "<PICKANDPLACEACTIONGOAL>"
   "PICKANDPLACEACTIONGOAL"
   "<PICKANDPLACEACTIONRESULT>"
   "PICKANDPLACEACTIONRESULT"
   "<PICKANDPLACEFEEDBACK>"
   "PICKANDPLACEFEEDBACK"
   "<PICKANDPLACEGOAL>"
   "PICKANDPLACEGOAL"
   "<PICKANDPLACERESULT>"
   "PICKANDPLACERESULT"
   "<OBJECTDETECTION>"
   "OBJECTDETECTION"
  ))

