// Generated by gencpp from file my_demo/PickPlaceFeedback.msg
// DO NOT EDIT!


#ifndef MY_DEMO_MESSAGE_PICKPLACEFEEDBACK_H
#define MY_DEMO_MESSAGE_PICKPLACEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_demo
{
template <class ContainerAllocator>
struct PickPlaceFeedback_
{
  typedef PickPlaceFeedback_<ContainerAllocator> Type;

  PickPlaceFeedback_()
    : progress(0)  {
    }
  PickPlaceFeedback_(const ContainerAllocator& _alloc)
    : progress(0)  {
  (void)_alloc;
    }



   typedef int32_t _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::my_demo::PickPlaceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_demo::PickPlaceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PickPlaceFeedback_

typedef ::my_demo::PickPlaceFeedback_<std::allocator<void> > PickPlaceFeedback;

typedef boost::shared_ptr< ::my_demo::PickPlaceFeedback > PickPlaceFeedbackPtr;
typedef boost::shared_ptr< ::my_demo::PickPlaceFeedback const> PickPlaceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_demo::PickPlaceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_demo::PickPlaceFeedback_<ContainerAllocator1> & lhs, const ::my_demo::PickPlaceFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_demo::PickPlaceFeedback_<ContainerAllocator1> & lhs, const ::my_demo::PickPlaceFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_demo::PickPlaceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_demo::PickPlaceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_demo::PickPlaceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3068c2ff8fa67c9565c90bbf9331baeb";
  }

  static const char* value(const ::my_demo::PickPlaceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3068c2ff8fa67c95ULL;
  static const uint64_t static_value2 = 0x65c90bbf9331baebULL;
};

template<class ContainerAllocator>
struct DataType< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_demo/PickPlaceFeedback";
  }

  static const char* value(const ::my_demo::PickPlaceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 3. FEEDBACK (Wat de robot tijdens het bewegen stuurt - mag leeg blijven)\n"
"int32 progress\n"
;
  }

  static const char* value(const ::my_demo::PickPlaceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickPlaceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_demo::PickPlaceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_demo::PickPlaceFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<int32_t>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DEMO_MESSAGE_PICKPLACEFEEDBACK_H
