(cl:defpackage my_demo-msg
  (:use )
  (:export
   "<PICKPLACEACTION>"
   "PICKPLACEACTION"
   "<PICKPLACEACTIONFEEDBACK>"
   "PICKPLACEACTIONFEEDBACK"
   "<PICKPLACEACTIONGOAL>"
   "PICKPLACEACTIONGOAL"
   "<PICKPLACEACTIONRESULT>"
   "PICKPLACEACTIONRESULT"
   "<PICKPLACEFEEDBACK>"
   "PICKPLACEFEEDBACK"
   "<PICKPLACEGOAL>"
   "PICKPLACEGOAL"
   "<PICKPLACERESULT>"
   "PICKPLACERESULT"
  ))

