; Auto-generated. Do not edit!


(cl:in-package my_demo-msg)


;//! \htmlinclude PickPlaceFeedback.msg.html

(cl:defclass <PickPlaceFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:integer
    :initform 0))
)

(cl:defclass PickPlaceFeedback (<PickPlaceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickPlaceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickPlaceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_demo-msg:<PickPlaceFeedback> is deprecated: use my_demo-msg:PickPlaceFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <PickPlaceFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_demo-msg:progress-val is deprecated.  Use my_demo-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickPlaceFeedback>) ostream)
  "Serializes a message object of type '<PickPlaceFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'progress)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickPlaceFeedback>) istream)
  "Deserializes a message object of type '<PickPlaceFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'progress) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickPlaceFeedback>)))
  "Returns string type for a message object of type '<PickPlaceFeedback>"
  "my_demo/PickPlaceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickPlaceFeedback)))
  "Returns string type for a message object of type 'PickPlaceFeedback"
  "my_demo/PickPlaceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickPlaceFeedback>)))
  "Returns md5sum for a message object of type '<PickPlaceFeedback>"
  "3068c2ff8fa67c9565c90bbf9331baeb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickPlaceFeedback)))
  "Returns md5sum for a message object of type 'PickPlaceFeedback"
  "3068c2ff8fa67c9565c90bbf9331baeb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickPlaceFeedback>)))
  "Returns full string definition for message of type '<PickPlaceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 3. FEEDBACK (Wat de robot tijdens het bewegen stuurt - mag leeg blijven)~%int32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickPlaceFeedback)))
  "Returns full string definition for message of type 'PickPlaceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 3. FEEDBACK (Wat de robot tijdens het bewegen stuurt - mag leeg blijven)~%int32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickPlaceFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickPlaceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PickPlaceFeedback
    (cl:cons ':progress (progress msg))
))
