// Generated by gencpp from file my_depthai/DetectObjectResponse.msg
// DO NOT EDIT!


#ifndef MY_DEPTHAI_MESSAGE_DETECTOBJECTRESPONSE_H
#define MY_DEPTHAI_MESSAGE_DETECTOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace my_depthai
{
template <class ContainerAllocator>
struct DetectObjectResponse_
{
  typedef DetectObjectResponse_<ContainerAllocator> Type;

  DetectObjectResponse_()
    : success(false)
    , object_class()
    , message()
    , pick_pose()  {
    }
  DetectObjectResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , object_class(_alloc)
    , message(_alloc)
    , pick_pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_class_type;
  _object_class_type object_class;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pick_pose_type;
  _pick_pose_type pick_pose;





  typedef boost::shared_ptr< ::my_depthai::DetectObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_depthai::DetectObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectResponse_

typedef ::my_depthai::DetectObjectResponse_<std::allocator<void> > DetectObjectResponse;

typedef boost::shared_ptr< ::my_depthai::DetectObjectResponse > DetectObjectResponsePtr;
typedef boost::shared_ptr< ::my_depthai::DetectObjectResponse const> DetectObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_depthai::DetectObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_depthai::DetectObjectResponse_<ContainerAllocator1> & lhs, const ::my_depthai::DetectObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.object_class == rhs.object_class &&
    lhs.message == rhs.message &&
    lhs.pick_pose == rhs.pick_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_depthai::DetectObjectResponse_<ContainerAllocator1> & lhs, const ::my_depthai::DetectObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_depthai

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_depthai::DetectObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_depthai::DetectObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_depthai::DetectObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b95455854c5d28811eaccdf7054b9b90";
  }

  static const char* value(const ::my_depthai::DetectObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb95455854c5d2881ULL;
  static const uint64_t static_value2 = 0x1eaccdf7054b9b90ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_depthai/DetectObjectResponse";
  }

  static const char* value(const ::my_depthai::DetectObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success\n"
"string object_class\n"
"string message\n"
"geometry_msgs/PoseStamped pick_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_depthai::DetectObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.object_class);
      stream.next(m.message);
      stream.next(m.pick_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_depthai::DetectObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_depthai::DetectObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "object_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_class);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "pick_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pick_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DEPTHAI_MESSAGE_DETECTOBJECTRESPONSE_H
