// Generated by gencpp from file my_depthai/DetectObjectRequest.msg
// DO NOT EDIT!


#ifndef MY_DEPTHAI_MESSAGE_DETECTOBJECTREQUEST_H
#define MY_DEPTHAI_MESSAGE_DETECTOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_depthai
{
template <class ContainerAllocator>
struct DetectObjectRequest_
{
  typedef DetectObjectRequest_<ContainerAllocator> Type;

  DetectObjectRequest_()
    {
    }
  DetectObjectRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::my_depthai::DetectObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_depthai::DetectObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectRequest_

typedef ::my_depthai::DetectObjectRequest_<std::allocator<void> > DetectObjectRequest;

typedef boost::shared_ptr< ::my_depthai::DetectObjectRequest > DetectObjectRequestPtr;
typedef boost::shared_ptr< ::my_depthai::DetectObjectRequest const> DetectObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_depthai::DetectObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace my_depthai

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_depthai::DetectObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_depthai::DetectObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_depthai::DetectObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::my_depthai::DetectObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_depthai/DetectObjectRequest";
  }

  static const char* value(const ::my_depthai::DetectObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: leeg — gewoon triggeren is genoeg\n"
;
  }

  static const char* value(const ::my_depthai::DetectObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_depthai::DetectObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::my_depthai::DetectObjectRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MY_DEPTHAI_MESSAGE_DETECTOBJECTREQUEST_H
