// Generated by gencpp from file my_depthai/DetectObject.msg
// DO NOT EDIT!


#ifndef MY_DEPTHAI_MESSAGE_DETECTOBJECT_H
#define MY_DEPTHAI_MESSAGE_DETECTOBJECT_H

#include <ros/service_traits.h>


#include <my_depthai/DetectObjectRequest.h>
#include <my_depthai/DetectObjectResponse.h>


namespace my_depthai
{

struct DetectObject
{

typedef DetectObjectRequest Request;
typedef DetectObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectObject
} // namespace my_depthai


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_depthai::DetectObject > {
  static const char* value()
  {
    return "b95455854c5d28811eaccdf7054b9b90";
  }

  static const char* value(const ::my_depthai::DetectObject&) { return value(); }
};

template<>
struct DataType< ::my_depthai::DetectObject > {
  static const char* value()
  {
    return "my_depthai/DetectObject";
  }

  static const char* value(const ::my_depthai::DetectObject&) { return value(); }
};


// service_traits::MD5Sum< ::my_depthai::DetectObjectRequest> should match
// service_traits::MD5Sum< ::my_depthai::DetectObject >
template<>
struct MD5Sum< ::my_depthai::DetectObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_depthai::DetectObject >::value();
  }
  static const char* value(const ::my_depthai::DetectObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_depthai::DetectObjectRequest> should match
// service_traits::DataType< ::my_depthai::DetectObject >
template<>
struct DataType< ::my_depthai::DetectObjectRequest>
{
  static const char* value()
  {
    return DataType< ::my_depthai::DetectObject >::value();
  }
  static const char* value(const ::my_depthai::DetectObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_depthai::DetectObjectResponse> should match
// service_traits::MD5Sum< ::my_depthai::DetectObject >
template<>
struct MD5Sum< ::my_depthai::DetectObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_depthai::DetectObject >::value();
  }
  static const char* value(const ::my_depthai::DetectObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_depthai::DetectObjectResponse> should match
// service_traits::DataType< ::my_depthai::DetectObject >
template<>
struct DataType< ::my_depthai::DetectObjectResponse>
{
  static const char* value()
  {
    return DataType< ::my_depthai::DetectObject >::value();
  }
  static const char* value(const ::my_depthai::DetectObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_DEPTHAI_MESSAGE_DETECTOBJECT_H
