// Generated by gencpp from file hoofdprogramma/ConveyorControl.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROL_H
#define HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROL_H

#include <ros/service_traits.h>


#include <hoofdprogramma/ConveyorControlRequest.h>
#include <hoofdprogramma/ConveyorControlResponse.h>


namespace hoofdprogramma
{

struct ConveyorControl
{

typedef ConveyorControlRequest Request;
typedef ConveyorControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConveyorControl
} // namespace hoofdprogramma


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hoofdprogramma::ConveyorControl > {
  static const char* value()
  {
    return "ab9233f15f98750719655c215d2e9e94";
  }

  static const char* value(const ::hoofdprogramma::ConveyorControl&) { return value(); }
};

template<>
struct DataType< ::hoofdprogramma::ConveyorControl > {
  static const char* value()
  {
    return "hoofdprogramma/ConveyorControl";
  }

  static const char* value(const ::hoofdprogramma::ConveyorControl&) { return value(); }
};


// service_traits::MD5Sum< ::hoofdprogramma::ConveyorControlRequest> should match
// service_traits::MD5Sum< ::hoofdprogramma::ConveyorControl >
template<>
struct MD5Sum< ::hoofdprogramma::ConveyorControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::ConveyorControl >::value();
  }
  static const char* value(const ::hoofdprogramma::ConveyorControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::ConveyorControlRequest> should match
// service_traits::DataType< ::hoofdprogramma::ConveyorControl >
template<>
struct DataType< ::hoofdprogramma::ConveyorControlRequest>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::ConveyorControl >::value();
  }
  static const char* value(const ::hoofdprogramma::ConveyorControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hoofdprogramma::ConveyorControlResponse> should match
// service_traits::MD5Sum< ::hoofdprogramma::ConveyorControl >
template<>
struct MD5Sum< ::hoofdprogramma::ConveyorControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::ConveyorControl >::value();
  }
  static const char* value(const ::hoofdprogramma::ConveyorControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::ConveyorControlResponse> should match
// service_traits::DataType< ::hoofdprogramma::ConveyorControl >
template<>
struct DataType< ::hoofdprogramma::ConveyorControlResponse>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::ConveyorControl >::value();
  }
  static const char* value(const ::hoofdprogramma::ConveyorControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROL_H
