// Generated by gencpp from file hoofdprogramma/ConveyorControlRequest.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROLREQUEST_H
#define HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct ConveyorControlRequest_
{
  typedef ConveyorControlRequest_<ContainerAllocator> Type;

  ConveyorControlRequest_()
    : run(false)  {
    }
  ConveyorControlRequest_(const ContainerAllocator& _alloc)
    : run(false)  {
  (void)_alloc;
    }



   typedef uint8_t _run_type;
  _run_type run;





  typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorControlRequest_

typedef ::hoofdprogramma::ConveyorControlRequest_<std::allocator<void> > ConveyorControlRequest;

typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlRequest > ConveyorControlRequestPtr;
typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlRequest const> ConveyorControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.run == rhs.run;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec9dd3a924ef46b6d608cc3c79a69713";
  }

  static const char* value(const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec9dd3a924ef46b6ULL;
  static const uint64_t static_value2 = 0xd608cc3c79a69713ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/ConveyorControlRequest";
  }

  static const char* value(const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool run\n"
;
  }

  static const char* value(const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.run);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::ConveyorControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROLREQUEST_H
