// Generated by gencpp from file hoofdprogramma/ConveyorControlResponse.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROLRESPONSE_H
#define HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct ConveyorControlResponse_
{
  typedef ConveyorControlResponse_<ContainerAllocator> Type;

  ConveyorControlResponse_()
    : success(false)
    , message()
    , state()  {
    }
  ConveyorControlResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorControlResponse_

typedef ::hoofdprogramma::ConveyorControlResponse_<std::allocator<void> > ConveyorControlResponse;

typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlResponse > ConveyorControlResponsePtr;
typedef boost::shared_ptr< ::hoofdprogramma::ConveyorControlResponse const> ConveyorControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator1> & lhs, const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator1> & lhs, const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e883716c8ff1d9b09f97a4888a1b25c3";
  }

  static const char* value(const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe883716c8ff1d9b0ULL;
  static const uint64_t static_value2 = 0x9f97a4888a1b25c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/ConveyorControlResponse";
  }

  static const char* value(const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"string state\n"
"\n"
;
  }

  static const char* value(const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::ConveyorControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_CONVEYORCONTROLRESPONSE_H
