// Generated by gencpp from file hoofdprogramma/objectDetection.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_OBJECTDETECTION_H
#define HOOFDPROGRAMMA_MESSAGE_OBJECTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace hoofdprogramma
{
template <class ContainerAllocator>
struct objectDetection_
{
  typedef objectDetection_<ContainerAllocator> Type;

  objectDetection_()
    : object_type()
    , pose()
    , confidence(0.0)  {
    }
  objectDetection_(const ContainerAllocator& _alloc)
    : object_type(_alloc)
    , pose(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_type_type;
  _object_type_type object_type;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::hoofdprogramma::objectDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::objectDetection_<ContainerAllocator> const> ConstPtr;

}; // struct objectDetection_

typedef ::hoofdprogramma::objectDetection_<std::allocator<void> > objectDetection;

typedef boost::shared_ptr< ::hoofdprogramma::objectDetection > objectDetectionPtr;
typedef boost::shared_ptr< ::hoofdprogramma::objectDetection const> objectDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::objectDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::objectDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::objectDetection_<ContainerAllocator1> & lhs, const ::hoofdprogramma::objectDetection_<ContainerAllocator2> & rhs)
{
  return lhs.object_type == rhs.object_type &&
    lhs.pose == rhs.pose &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::objectDetection_<ContainerAllocator1> & lhs, const ::hoofdprogramma::objectDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::objectDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::objectDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::objectDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51cf1d8d3850a43ca6b509aa1916ae48";
  }

  static const char* value(const ::hoofdprogramma::objectDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51cf1d8d3850a43cULL;
  static const uint64_t static_value2 = 0xa6b509aa1916ae48ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/objectDetection";
  }

  static const char* value(const ::hoofdprogramma::objectDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_type\n"
"geometry_msgs/Pose pose\n"
"float32 confidence\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::hoofdprogramma::objectDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_type);
      stream.next(m.pose);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objectDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::objectDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::objectDetection_<ContainerAllocator>& v)
  {
    s << indent << "object_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_type);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_OBJECTDETECTION_H
