// Generated by gencpp from file hoofdprogramma/PickAndPlaceFeedback.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_PICKANDPLACEFEEDBACK_H
#define HOOFDPROGRAMMA_MESSAGE_PICKANDPLACEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct PickAndPlaceFeedback_
{
  typedef PickAndPlaceFeedback_<ContainerAllocator> Type;

  PickAndPlaceFeedback_()
    : progress(0.0)
    , state()  {
    }
  PickAndPlaceFeedback_(const ContainerAllocator& _alloc)
    : progress(0.0)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef float _progress_type;
  _progress_type progress;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PickAndPlaceFeedback_

typedef ::hoofdprogramma::PickAndPlaceFeedback_<std::allocator<void> > PickAndPlaceFeedback;

typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceFeedback > PickAndPlaceFeedbackPtr;
typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceFeedback const> PickAndPlaceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator1> & lhs, const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator1> & lhs, const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5953f5915e43994543b2e1a00947b194";
  }

  static const char* value(const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5953f5915e439945ULL;
  static const uint64_t static_value2 = 0x43b2e1a00947b194ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/PickAndPlaceFeedback";
  }

  static const char* value(const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 progress\n"
"string state\n"
;
  }

  static const char* value(const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickAndPlaceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::PickAndPlaceFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_PICKANDPLACEFEEDBACK_H
