// Generated by gencpp from file hoofdprogramma/ResetCyclus.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_RESETCYCLUS_H
#define HOOFDPROGRAMMA_MESSAGE_RESETCYCLUS_H

#include <ros/service_traits.h>


#include <hoofdprogramma/ResetCyclusRequest.h>
#include <hoofdprogramma/ResetCyclusResponse.h>


namespace hoofdprogramma
{

struct ResetCyclus
{

typedef ResetCyclusRequest Request;
typedef ResetCyclusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetCyclus
} // namespace hoofdprogramma


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hoofdprogramma::ResetCyclus > {
  static const char* value()
  {
    return "51cbeac084f3f5882dc2b7d6b3318d43";
  }

  static const char* value(const ::hoofdprogramma::ResetCyclus&) { return value(); }
};

template<>
struct DataType< ::hoofdprogramma::ResetCyclus > {
  static const char* value()
  {
    return "hoofdprogramma/ResetCyclus";
  }

  static const char* value(const ::hoofdprogramma::ResetCyclus&) { return value(); }
};


// service_traits::MD5Sum< ::hoofdprogramma::ResetCyclusRequest> should match
// service_traits::MD5Sum< ::hoofdprogramma::ResetCyclus >
template<>
struct MD5Sum< ::hoofdprogramma::ResetCyclusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::ResetCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::ResetCyclusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::ResetCyclusRequest> should match
// service_traits::DataType< ::hoofdprogramma::ResetCyclus >
template<>
struct DataType< ::hoofdprogramma::ResetCyclusRequest>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::ResetCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::ResetCyclusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hoofdprogramma::ResetCyclusResponse> should match
// service_traits::MD5Sum< ::hoofdprogramma::ResetCyclus >
template<>
struct MD5Sum< ::hoofdprogramma::ResetCyclusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::ResetCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::ResetCyclusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::ResetCyclusResponse> should match
// service_traits::DataType< ::hoofdprogramma::ResetCyclus >
template<>
struct DataType< ::hoofdprogramma::ResetCyclusResponse>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::ResetCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::ResetCyclusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_RESETCYCLUS_H
