// Generated by gencpp from file hoofdprogramma/ResetCyclusRequest.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_RESETCYCLUSREQUEST_H
#define HOOFDPROGRAMMA_MESSAGE_RESETCYCLUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct ResetCyclusRequest_
{
  typedef ResetCyclusRequest_<ContainerAllocator> Type;

  ResetCyclusRequest_()
    : reset(false)  {
    }
  ResetCyclusRequest_(const ContainerAllocator& _alloc)
    : reset(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetCyclusRequest_

typedef ::hoofdprogramma::ResetCyclusRequest_<std::allocator<void> > ResetCyclusRequest;

typedef boost::shared_ptr< ::hoofdprogramma::ResetCyclusRequest > ResetCyclusRequestPtr;
typedef boost::shared_ptr< ::hoofdprogramma::ResetCyclusRequest const> ResetCyclusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba4b0b221fb425ac5eaf73f71ae34971";
  }

  static const char* value(const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba4b0b221fb425acULL;
  static const uint64_t static_value2 = 0x5eaf73f71ae34971ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/ResetCyclusRequest";
  }

  static const char* value(const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset\n"
;
  }

  static const char* value(const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetCyclusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::ResetCyclusRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_RESETCYCLUSREQUEST_H
