// Generated by gencpp from file hoofdprogramma/SingleStart.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_SINGLESTART_H
#define HOOFDPROGRAMMA_MESSAGE_SINGLESTART_H

#include <ros/service_traits.h>


#include <hoofdprogramma/SingleStartRequest.h>
#include <hoofdprogramma/SingleStartResponse.h>


namespace hoofdprogramma
{

struct SingleStart
{

typedef SingleStartRequest Request;
typedef SingleStartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SingleStart
} // namespace hoofdprogramma


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hoofdprogramma::SingleStart > {
  static const char* value()
  {
    return "570b7d04f9d3b17893f17c4fdcf5ca06";
  }

  static const char* value(const ::hoofdprogramma::SingleStart&) { return value(); }
};

template<>
struct DataType< ::hoofdprogramma::SingleStart > {
  static const char* value()
  {
    return "hoofdprogramma/SingleStart";
  }

  static const char* value(const ::hoofdprogramma::SingleStart&) { return value(); }
};


// service_traits::MD5Sum< ::hoofdprogramma::SingleStartRequest> should match
// service_traits::MD5Sum< ::hoofdprogramma::SingleStart >
template<>
struct MD5Sum< ::hoofdprogramma::SingleStartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::SingleStart >::value();
  }
  static const char* value(const ::hoofdprogramma::SingleStartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::SingleStartRequest> should match
// service_traits::DataType< ::hoofdprogramma::SingleStart >
template<>
struct DataType< ::hoofdprogramma::SingleStartRequest>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::SingleStart >::value();
  }
  static const char* value(const ::hoofdprogramma::SingleStartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hoofdprogramma::SingleStartResponse> should match
// service_traits::MD5Sum< ::hoofdprogramma::SingleStart >
template<>
struct MD5Sum< ::hoofdprogramma::SingleStartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::SingleStart >::value();
  }
  static const char* value(const ::hoofdprogramma::SingleStartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::SingleStartResponse> should match
// service_traits::DataType< ::hoofdprogramma::SingleStart >
template<>
struct DataType< ::hoofdprogramma::SingleStartResponse>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::SingleStart >::value();
  }
  static const char* value(const ::hoofdprogramma::SingleStartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_SINGLESTART_H
