// Generated by gencpp from file hoofdprogramma/SingleStartRequest.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_SINGLESTARTREQUEST_H
#define HOOFDPROGRAMMA_MESSAGE_SINGLESTARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct SingleStartRequest_
{
  typedef SingleStartRequest_<ContainerAllocator> Type;

  SingleStartRequest_()
    : start(false)  {
    }
  SingleStartRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SingleStartRequest_

typedef ::hoofdprogramma::SingleStartRequest_<std::allocator<void> > SingleStartRequest;

typedef boost::shared_ptr< ::hoofdprogramma::SingleStartRequest > SingleStartRequestPtr;
typedef boost::shared_ptr< ::hoofdprogramma::SingleStartRequest const> SingleStartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/SingleStartRequest";
  }

  static const char* value(const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
;
  }

  static const char* value(const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SingleStartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::SingleStartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::SingleStartRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_SINGLESTARTREQUEST_H
