// Generated by gencpp from file hoofdprogramma/StartCyclus.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_STARTCYCLUS_H
#define HOOFDPROGRAMMA_MESSAGE_STARTCYCLUS_H

#include <ros/service_traits.h>


#include <hoofdprogramma/StartCyclusRequest.h>
#include <hoofdprogramma/StartCyclusResponse.h>


namespace hoofdprogramma
{

struct StartCyclus
{

typedef StartCyclusRequest Request;
typedef StartCyclusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartCyclus
} // namespace hoofdprogramma


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hoofdprogramma::StartCyclus > {
  static const char* value()
  {
    return "51224950c96b81351ba7f238527c827f";
  }

  static const char* value(const ::hoofdprogramma::StartCyclus&) { return value(); }
};

template<>
struct DataType< ::hoofdprogramma::StartCyclus > {
  static const char* value()
  {
    return "hoofdprogramma/StartCyclus";
  }

  static const char* value(const ::hoofdprogramma::StartCyclus&) { return value(); }
};


// service_traits::MD5Sum< ::hoofdprogramma::StartCyclusRequest> should match
// service_traits::MD5Sum< ::hoofdprogramma::StartCyclus >
template<>
struct MD5Sum< ::hoofdprogramma::StartCyclusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::StartCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StartCyclusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::StartCyclusRequest> should match
// service_traits::DataType< ::hoofdprogramma::StartCyclus >
template<>
struct DataType< ::hoofdprogramma::StartCyclusRequest>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::StartCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StartCyclusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hoofdprogramma::StartCyclusResponse> should match
// service_traits::MD5Sum< ::hoofdprogramma::StartCyclus >
template<>
struct MD5Sum< ::hoofdprogramma::StartCyclusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::StartCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StartCyclusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::StartCyclusResponse> should match
// service_traits::DataType< ::hoofdprogramma::StartCyclus >
template<>
struct DataType< ::hoofdprogramma::StartCyclusResponse>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::StartCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StartCyclusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_STARTCYCLUS_H
