// Generated by gencpp from file hoofdprogramma/StartCyclusRequest.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_STARTCYCLUSREQUEST_H
#define HOOFDPROGRAMMA_MESSAGE_STARTCYCLUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct StartCyclusRequest_
{
  typedef StartCyclusRequest_<ContainerAllocator> Type;

  StartCyclusRequest_()
    : object_type()
    , reset(false)  {
    }
  StartCyclusRequest_(const ContainerAllocator& _alloc)
    : object_type(_alloc)
    , reset(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_type_type;
  _object_type_type object_type;

   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartCyclusRequest_

typedef ::hoofdprogramma::StartCyclusRequest_<std::allocator<void> > StartCyclusRequest;

typedef boost::shared_ptr< ::hoofdprogramma::StartCyclusRequest > StartCyclusRequestPtr;
typedef boost::shared_ptr< ::hoofdprogramma::StartCyclusRequest const> StartCyclusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_type == rhs.object_type &&
    lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60875a7ea2b59bdae48f81a727cbffcb";
  }

  static const char* value(const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60875a7ea2b59bdaULL;
  static const uint64_t static_value2 = 0xe48f81a727cbffcbULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/StartCyclusRequest";
  }

  static const char* value(const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_type\n"
"bool reset\n"
;
  }

  static const char* value(const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_type);
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartCyclusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::StartCyclusRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_type);
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_STARTCYCLUSREQUEST_H
