// Generated by gencpp from file hoofdprogramma/StopCyclusRequest.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_STOPCYCLUSREQUEST_H
#define HOOFDPROGRAMMA_MESSAGE_STOPCYCLUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct StopCyclusRequest_
{
  typedef StopCyclusRequest_<ContainerAllocator> Type;

  StopCyclusRequest_()
    : stop(false)  {
    }
  StopCyclusRequest_(const ContainerAllocator& _alloc)
    : stop(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stop_type;
  _stop_type stop;





  typedef boost::shared_ptr< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopCyclusRequest_

typedef ::hoofdprogramma::StopCyclusRequest_<std::allocator<void> > StopCyclusRequest;

typedef boost::shared_ptr< ::hoofdprogramma::StopCyclusRequest > StopCyclusRequestPtr;
typedef boost::shared_ptr< ::hoofdprogramma::StopCyclusRequest const> StopCyclusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.stop == rhs.stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator1> & lhs, const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71f1172402e56b82716ca71681cded6b";
  }

  static const char* value(const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71f1172402e56b82ULL;
  static const uint64_t static_value2 = 0x716ca71681cded6bULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/StopCyclusRequest";
  }

  static const char* value(const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stop\n"
;
  }

  static const char* value(const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopCyclusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::StopCyclusRequest_<ContainerAllocator>& v)
  {
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_STOPCYCLUSREQUEST_H
