// Generated by gencpp from file hoofdprogramma/StopCyclus.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_STOPCYCLUS_H
#define HOOFDPROGRAMMA_MESSAGE_STOPCYCLUS_H

#include <ros/service_traits.h>


#include <hoofdprogramma/StopCyclusRequest.h>
#include <hoofdprogramma/StopCyclusResponse.h>


namespace hoofdprogramma
{

struct StopCyclus
{

typedef StopCyclusRequest Request;
typedef StopCyclusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopCyclus
} // namespace hoofdprogramma


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hoofdprogramma::StopCyclus > {
  static const char* value()
  {
    return "7d3aaec1ad97cf89d115490df578ba5b";
  }

  static const char* value(const ::hoofdprogramma::StopCyclus&) { return value(); }
};

template<>
struct DataType< ::hoofdprogramma::StopCyclus > {
  static const char* value()
  {
    return "hoofdprogramma/StopCyclus";
  }

  static const char* value(const ::hoofdprogramma::StopCyclus&) { return value(); }
};


// service_traits::MD5Sum< ::hoofdprogramma::StopCyclusRequest> should match
// service_traits::MD5Sum< ::hoofdprogramma::StopCyclus >
template<>
struct MD5Sum< ::hoofdprogramma::StopCyclusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::StopCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StopCyclusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::StopCyclusRequest> should match
// service_traits::DataType< ::hoofdprogramma::StopCyclus >
template<>
struct DataType< ::hoofdprogramma::StopCyclusRequest>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::StopCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StopCyclusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hoofdprogramma::StopCyclusResponse> should match
// service_traits::MD5Sum< ::hoofdprogramma::StopCyclus >
template<>
struct MD5Sum< ::hoofdprogramma::StopCyclusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hoofdprogramma::StopCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StopCyclusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hoofdprogramma::StopCyclusResponse> should match
// service_traits::DataType< ::hoofdprogramma::StopCyclus >
template<>
struct DataType< ::hoofdprogramma::StopCyclusResponse>
{
  static const char* value()
  {
    return DataType< ::hoofdprogramma::StopCyclus >::value();
  }
  static const char* value(const ::hoofdprogramma::StopCyclusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_STOPCYCLUS_H
